### ISSUE TITLE
Unknown error code

### ISSUE THREAD

**Issue by aBARICHELLO** [colyseus/haxe-ws#2]
![image](https://user-images.githubusercontent.com/16687318/75640832-0ff4ee00-5c15-11ea-8a19-7351b20b7f14.png)
I get this output when trying to compile the example server code(examples are outdated fyi), I am creating a websocket server with isSecure false and isDebug true.

**Comment by aBARICHELLO** [comment]
Can https://github.com/colyseus/colyseus-hx be used as a websocket server instead of this fork of haxe-ws?

**Comment by endel** [comment]
Hi @aBARICHELLO, this project mainly focuses on maintaining the WebSocket **clients** up-to-date. For WebSocket **server** you should probably check out this: https://github.com/ianharrigan/hxWebSockets
