### ISSUE TITLE
Server example Python target - NameError: name 'sys_ssl_Socket' is not defined

### ISSUE THREAD

**Issue by mjedmonds** [colyseus/haxe-ws#5]
I'm getting a `NameError: name 'sys_ssl_Socket' is not defined` when adding a python target for the server example.

To reproduce:

1. Add 

```
--next

-python output/serverExamplePy.py
-cp src
-main haxe.net.example.WebSocketServerExample
```

to `serverExample.hxml`

2. `haxe serverExample.hxml`
3. `python output/serverExamplePy.py`

This results in the following traceback:

```
Traceback (most recent call last):
  File "output/serverExamplePy.py", line 3086, in <module>
    haxe_net_example_WebSocketServerExample.main()
  File "output/serverExamplePy.py", line 1375, in main
    server = haxe_net_WebSocketServer.create("0.0.0.0",port,1,True,False)
  File "output/serverExamplePy.py", line 1318, in create
    return haxe_net_WebSocketServer(host,port,maxConnections,isSecure,isDebug)
  File "output/serverExamplePy.py", line 1267, in __init__
    self._listenSocket = (sys_ssl_Socket() if (self._isSecure) else sys_net_Socket())
NameError: name 'sys_ssl_Socket' is not defined
```

Is this an issue with Haxe's python socket implementation? I'm new to haxe, so I'm not sure how to inspect this myself.

Thanks!

**Comment by endel** [comment]
Hi @mjedmonds, 

This fork of `haxe-ws` aims to support only WebSocket **client**, the server haven't been tested. As Colyseus does not currently have a Python client, the WebSocket client for Python haven't been tested too.

Have you tried this other implementation? https://github.com/ianharrigan/hxWebSockets
hxWebSockets was also a fork from `haxe-ws`, and now it evolved on its own thing AFAIK.

Hope this helps, cheers!

**Comment by mjedmonds** [comment]
Yes it does, thank you!
