### ISSUE TITLE
Getting a compilation failure for python target

### ISSUE THREAD

**Issue by skylerparr** [colyseus/haxe-ws#6]
Thank you for this project. I've gotten a lot of good usage out of it. I ran into this error when targeting the `python` target:
```
src/haxe/net/Crypto.hx:19: characters 29-37 : Type not found : RandomOs
```
I'm running ubuntu with both python2 and python3 installed on my machine, and using `master` of this git repo. Do I need to specify which python version to use during compilation? Are there other libraries that I need to install? Any help is greatly appreciated.

**Comment by endel** [comment]
Hi @skylerparr, this has been reported recently, and the latest version should have a fix for it: https://github.com/colyseus/haxe-ws/issues/4

As Colyseus do not have a Python client, I haven't personally tested this for Python. If you need a WebSocket Server, please see https://github.com/colyseus/haxe-ws/issues/5#issuecomment-658399439
